name: Tube MGM24 HW Zigbee
device: MGM240PA32VNN
base_project: src/ncp-uart-hw
filename: "{manifest_name}_{ezsp_version}"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_UART
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts
  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64

slcp_defines:
  EMBER_ADDRESS_TABLE_SIZE: 16
  EMBER_MULTICAST_TABLE_SIZE: 16

c_defines:
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_TX_PIN:  6

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  7

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortA
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  8

  # SL_APPLICATION_PRODUCT_ID: '{0x00}'

  SL_RAIL_UTIL_PTI_DOUT_PORT: gpioPortC
  SL_RAIL_UTIL_PTI_DOUT_PIN:  4

  SL_RAIL_UTIL_PTI_DFRAME_PORT: gpioPortC
  SL_RAIL_UTIL_PTI_DFRAME_PIN:  5

  EMBER_APS_UNICAST_MESSAGE_COUNT: 20
  EMBER_BROADCAST_TABLE_SIZE: 30
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254
